name: papaa
owner: vijay
description: "PAPAA - Pancancer Aberrant Pathway Activity Analysis a toolset for measuring aberrant pathway activity in TCGA."
homepage_url: http://github.com/nvk747/papaa
remote_repository_url: http://github.com/nvk747/papaa
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the papaa tool suite: {{ tool_name }}"
suite:
  name: "papaa_suite"
  description: "PAPAA toolset for measuring aberrant pathway activity in TCGA."
categories:
- Machine Learning
- Graphics
